package com.makanforyou.payment.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Payment Entity - Represents payment records for orders
 *
 * Database Table: payments
 * Primary Key: payment_id (Auto-Increment)
 *
 * Foreign Keys:
 * - order_id (UNIQUE) -> orders.order_id
 * - user_id -> users.user_id
 *
 * Dependencies:
 * - Each payment is linked to exactly one order
 * - Each payment belongs to exactly one user
 * - Payment can have multiple status transitions: PENDING -> COMPLETED -> REFUNDED
 */
@Entity
@Table(name = "payments", indexes = {
    @Index(name = "idx_order_id", columnList = "order_id"),
    @Index(name = "idx_user_id", columnList = "user_id"),
    @Index(name = "idx_payment_status", columnList = "payment_status"),
    @Index(name = "idx_payment_date", columnList = "payment_date")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {})
@EqualsAndHashCode(exclude = {})
public class Payment {

    /**
     * Unique identifier for the payment
     * Auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "payment_id")
    private Integer paymentId;

    /**
     * Reference to the order being paid for
     * UNIQUE constraint: One payment per order
     */
    @Column(name = "order_id", nullable = false, unique = true)
    private Integer orderId;

    /**
     * Reference to the user making the payment
     * Links to users table
     */
    @Column(name = "user_id", nullable = false)
    private Integer userId;

    /**
     * Amount being paid
     * Precision: 10 digits total, 2 decimal places (max: 99999999.99)
     */
    @Column(name = "payment_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal paymentAmount;

    /**
     * Method of payment
     * Values: CREDIT_CARD, DEBIT_CARD, NET_BANKING, WALLET, CASH_ON_DELIVERY, UPI
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 20)
    private PaymentMethod paymentMethod;

    /**
     * Current status of the payment
     * Values: PENDING, COMPLETED, FAILED, REFUNDED
     * Transitions: PENDING -> (COMPLETED or FAILED) -> (REFUNDED or terminal state)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 20)
    private PaymentStatus paymentStatus;

    /**
     * Transaction ID from payment gateway
     * Required for non-COD payments
     * Format: TXN-YYYY-XXXXXX
     */
    @Column(name = "transaction_id", length = 100)
    private String transactionId;

    /**
     * Timestamp when payment was processed
     * NULL if payment is still PENDING
     */
    @Column(name = "payment_date")
    private LocalDateTime paymentDate;

    /**
     * Amount refunded (if any)
     * Default: 0.00
     * Cannot exceed paymentAmount
     */
    @Column(name = "refund_amount", precision = 10, scale = 2)
    private BigDecimal refundAmount;

    /**
     * Timestamp when refund was processed
     * NULL if no refund has been issued
     */
    @Column(name = "refund_date")
    private LocalDateTime refundDate;

    /**
     * Reason for refund (if applicable)
     * Examples: "Order cancelled by customer", "Duplicate payment", "Customer request"
     */
    @Column(name = "refund_reason", columnDefinition = "TEXT")
    private String refundReason;

    /**
     * Timestamp when record was created
     * Set automatically by database
     * Not updatable
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when record was last updated
     * Updated automatically on any modification
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ============================================================
    // ENUMS
    // ============================================================

    /**
     * Payment status enum
     *
     * PENDING: Payment awaiting processing
     * COMPLETED: Payment successfully processed and confirmed
     * FAILED: Payment processing failed (requires retry)
     * REFUNDED: Payment has been refunded to customer
     */
    public enum PaymentStatus {
        PENDING,      // Initial state
        COMPLETED,    // Successful payment
        FAILED,       // Payment failed
        REFUNDED      // Payment refunded
    }

    /**
     * Payment method enum
     *
     * CREDIT_CARD: Credit card payment via payment gateway
     * DEBIT_CARD: Debit card payment via payment gateway
     * NET_BANKING: Direct bank transfer
     * WALLET: Digital wallet (PayTM, PhonePe, Google Pay, etc.)
     * CASH_ON_DELIVERY: Cash payment at delivery location
     * UPI: Unified Payments Interface (Immediate Online Transfer)
     */
    public enum PaymentMethod {
        CREDIT_CARD,
        DEBIT_CARD,
        NET_BANKING,
        WALLET,
        CASH_ON_DELIVERY,
        UPI
    }

    // ============================================================
    // HELPER METHODS
    // ============================================================

    /**
     * Check if payment has been completed
     */
    public boolean isCompleted() {
        return this.paymentStatus == PaymentStatus.COMPLETED;
    }

    /**
     * Check if payment can be refunded
     */
    public boolean canBeRefunded() {
        return this.paymentStatus == PaymentStatus.COMPLETED;
    }

    /**
     * Check if payment failed
     */
    public boolean isFailed() {
        return this.paymentStatus == PaymentStatus.FAILED;
    }

    /**
     * Check if payment requires manual intervention
     */
    public boolean requiresManualIntervention() {
        return this.paymentStatus == PaymentStatus.PENDING &&
               this.paymentDate != null &&
               this.paymentDate.isBefore(LocalDateTime.now().minusHours(1));
    }
}
