package com.makanforyou.delivery.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Delivery Entity - Represents delivery tracking for orders
 *
 * Database Table: deliveries
 * Primary Key: delivery_id (Auto-Increment)
 *
 * Foreign Keys:
 * - order_id (UNIQUE) -> orders.order_id
 * - kitchen_id -> kitchens.kitchen_id
 * - user_id -> users.user_id
 * - item_id -> kitchen_menu.item_id
 *
 * Dependencies:
 * - Each delivery is linked to exactly one order
 * - Each delivery originates from exactly one kitchen
 * - Each delivery is for exactly one customer (user)
 * - Each delivery contains exactly one menu item (item_id from order_items)
 * - Delivery status transitions: PENDING -> ASSIGNED -> PICKED_UP -> IN_TRANSIT -> DELIVERED or FAILED
 */
@Entity
@Table(name = "deliveries", indexes = {
    @Index(name = "idx_order_id", columnList = "order_id"),
    @Index(name = "idx_kitchen_id", columnList = "kitchen_id"),
    @Index(name = "idx_user_id", columnList = "user_id"),
    @Index(name = "idx_delivery_status", columnList = "delivery_status"),
    @Index(name = "idx_delivery_time", columnList = "delivery_time")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {})
@EqualsAndHashCode(exclude = {})
public class Delivery {

    /**
     * Unique identifier for the delivery
     * Auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "delivery_id")
    private Integer deliveryId;

    /**
     * Reference to the order being delivered
     * UNIQUE constraint: One delivery per order
     * Links to orders table
     */
    @Column(name = "order_id", nullable = false, unique = true)
    private Integer orderId;

    /**
     * Reference to the kitchen preparing the order
     * Links to kitchens table
     * Used to determine pickup location
     */
    @Column(name = "kitchen_id", nullable = false)
    private Integer kitchenId;

    /**
     * Reference to the customer receiving the delivery
     * Links to users table
     * Used for delivery address validation
     */
    @Column(name = "user_id", nullable = false)
    private Integer userId;

    /**
     * Reference to the menu item being delivered
     * Links to kitchen_menu table
     * Provides item details for delivery personnel
     */
    @Column(name = "item_id", nullable = false)
    private Integer itemId;

    /**
     * Current status of the delivery
     * Values: PENDING, ASSIGNED, PICKED_UP, IN_TRANSIT, DELIVERED, FAILED
     *
     * Transition Flow:
     * PENDING: Initial state, awaiting partner assignment
     * ASSIGNED: Delivery partner has been assigned
     * PICKED_UP: Order picked up from kitchen
     * IN_TRANSIT: On the way to customer
     * DELIVERED: Successfully delivered to customer
     * FAILED: Delivery attempt failed, manual intervention needed
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "delivery_status", nullable = false, length = 20)
    private DeliveryStatus deliveryStatus;

    /**
     * Name of delivery partner/agent
     * Set when delivery is assigned
     * Format: First Name Last Name
     */
    @Column(name = "assigned_to", length = 100)
    private String assignedTo;

    /**
     * Timestamp when order was picked up from kitchen
     * NULL until PICKED_UP status is set
     */
    @Column(name = "pickup_time")
    private LocalDateTime pickupTime;

    /**
     * Timestamp when delivery was completed
     * NULL until DELIVERED status is set
     */
    @Column(name = "delivery_time")
    private LocalDateTime deliveryTime;

    /**
     * Estimated time when delivery should be completed
     * Set when delivery record is created
     * Used to track on-time vs late deliveries
     * Format: ISO 8601 (e.g., 2026-02-03T12:00:00Z)
     */
    @Column(name = "estimated_delivery_time", nullable = false)
    private LocalDateTime estimatedDeliveryTime;

    /**
     * Current location of delivery
     * Updated as delivery progresses
     * Format: Can be address, coordinates, or landmark
     * Examples: "12.9716° N, 77.5946° E", "Customer location", "On Highway 5"
     */
    @Column(name = "current_location", length = 255)
    private String currentLocation;

    /**
     * Additional notes about the delivery
     * Examples:
     * - "Leave at gate if no one is home"
     * - "Call when arriving"
     * - "Customer not available at address"
     */
    @Column(name = "delivery_notes", columnDefinition = "TEXT")
    private String deliveryNotes;

    /**
     * Timestamp when record was created
     * Set automatically by database
     * Not updatable
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when record was last updated
     * Updated automatically on any modification
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ============================================================
    // ENUMS
    // ============================================================

    /**
     * Delivery status enum
     *
     * PENDING: Initial state, awaiting partner assignment
     * ASSIGNED: Delivery partner assigned, waiting for pickup
     * PICKED_UP: Order picked up from kitchen, on the way
     * IN_TRANSIT: Actively being delivered to customer
     * DELIVERED: Successfully delivered to customer
     * FAILED: Delivery failed, needs intervention or retry
     */
    public enum DeliveryStatus {
        PENDING,           // 1. Awaiting partner assignment
        ASSIGNED,          // 2. Partner assigned
        PICKED_UP,         // 3. Picked up from kitchen
        IN_TRANSIT,        // 4. On the way to customer
        DELIVERED,         // 5. Successfully delivered (terminal)
        FAILED             // 6. Failed delivery (needs retry or intervention)
    }

    // ============================================================
    // HELPER METHODS
    // ============================================================

    /**
     * Check if delivery has been completed successfully
     */
    public boolean isDelivered() {
        return this.deliveryStatus == DeliveryStatus.DELIVERED;
    }

    /**
     * Check if delivery has failed
     */
    public boolean hasFailed() {
        return this.deliveryStatus == DeliveryStatus.FAILED;
    }

    /**
     * Check if delivery is in progress
     */
    public boolean isInProgress() {
        return this.deliveryStatus == DeliveryStatus.IN_TRANSIT;
    }

    /**
     * Check if delivery is awaiting assignment
     */
    public boolean isPending() {
        return this.deliveryStatus == DeliveryStatus.PENDING;
    }

    /**
     * Check if delivery is late (current time > estimated time)
     */
    public boolean isLate() {
        if (this.estimatedDeliveryTime == null) {
            return false;
        }
        return LocalDateTime.now().isAfter(this.estimatedDeliveryTime);
    }

    /**
     * Calculate delivery duration in minutes
     * Returns -1 if delivery not yet completed
     */
    public long getDeliveryDurationMinutes() {
        if (this.pickupTime == null || this.deliveryTime == null) {
            return -1;
        }
        return java.time.temporal.ChronoUnit.MINUTES.between(this.pickupTime, this.deliveryTime);
    }

    /**
     * Check if delivery was on time
     * True if deliveryTime <= estimatedDeliveryTime
     */
    public boolean wasOnTime() {
        if (this.deliveryTime == null || this.estimatedDeliveryTime == null) {
            return false;
        }
        return this.deliveryTime.isBefore(this.estimatedDeliveryTime) ||
               this.deliveryTime.isEqual(this.estimatedDeliveryTime);
    }
}
